### ISSUE TITLE
[Fanout Tracking] package-security - Proxima Services Fully Functional in the Australia Stamp

### ISSUE THREAD

**Issue by its-mia** [github/actions-oidc-gateway-example#6]
### Fanout Effort

https://github.com/github/fanout/issues/1541

### 🚦 Status

|Field|Value
|-----|-----|
|Trending|⚪ inactive|
|Company Priority|Priority 1|

### 🧳 Accountability

|Field|Value
|-----|-----|
|Exec Sponsor|nerdneha|
|DRI| @trevrosen  |
|Product Area||

### 📅 Key Dates

|Field|Value
|-----|-----|
|Start Date|2024-05-15|
|Target Date|2024-06-30|
|Last Report Date||

### 🏔 Fanout Summary

In Q3FY24 we have successfully onboarded our external Alpha customers in the EU stamp. In Q4FY24 , we are expanding beyond EU and turning our attention to our [regional roll out](https://github.com/github/proxima/blob/main/planning/Proxima%20Region%20Plan.md) starting with the Australia stamp. In order to do this, we are asking all the teams to be fully functional in the Australia Stamp, prioritize automation, and record the time to stand up infrastructure and become fully functional.

### 📈 Overview of the Requested Work

We are expecting at least 4 additional stamps in FY25 and more in FY26. Therefore, as part of building out the AUS stamp this quarter, teams should plan and investigate automation to make future stamp creation faster so that we can achieve these goals. This is the first time both infrastructure and services are getting onboarded during the same quarter. As such teams should be aware of the timing. Infrastructure will be deployed during the first month of the quarter and service teams will be able to start onboarding from May 15, 2024 or sooner. We will communicate the changes in the Fanout issue when the Australia stamp infrastructure is ready for service onboarding. Until then, the Fanout issue status stays inactive.

> [!IMPORTANT] 
> *  Teams should plan and implement opportunistic high-ROI automation this quarter. The planning work for this can start before infrastructure is ready on May 15th, 2024 (or sooner). 
> *  As part of this Fanout, we request teams should document the duration and developer resources required to 1) stand up any additional infrastructure your team uses and 2) achieve full functionality in AUS including end to end testing. Please include this information in [this spreadsheet ](https://docs.google.com/spreadsheets/d/1GS227JrntqLBkHbDYwIQfFAGAOmwuMvtXLGmnxJU6a0/edit#gid=0)before marking this issue as closed.
> * We are expecting at least 4 additional stamps in FY25 and more in FY26. Please document particular areas where **_automation_** can streamline future onboarding for your team, along with an estimated effort for implementing such automation and the anticipated time savings before closing this issue. Alternatively, if the automation is feasible within the quarter, consider building the automation first and then using it to spin up this stamp.

### 🚦 Success Target

The DRI will provide weekly updates by Wednesday 5 PM PT for each of the Fanout issues. 
Updates are submitted in this Fanout issue by calling the `/short-report` issue comment template.

###  📝 Supporting Materials

- [Fully Functional Service Guidance](https://github.com/github/proxima/blob/main/docs/guides/fully%20functional%20service%20guidance.md)
- [New Stamp creation playbook](https://github.com/github/proxima/tree/main/docs/playbooks/new-stamp-creation#new-stamp-creation-playbook)
- [Heaven Pipelines Onboarding](https://thehub.github.com/epd/engineering/devops/deployment/onboarding-to-heaven-pipelines/)
- [Proxima Observability Guidance](https://thehub.github.com/epd/engineering/products-and-services/proxima/observability/)
- For support, there are various `#proxima-*` channels depending on what is needed.
- For help with deployments or pipeline updates come by [#deploy-support](https://github.slack.com/archives/CECRLG4LQ).
- For observability help use [#observability](https://github.slack.com/archives/C9H0UJC2W).
- For tenancy questions stop by [#proxima-tenancy](https://github.slack.com/archives/C02TQDUV4M6).

### ✔️ Tasklist

```[tasklist]
### Tasks
- [ ] Your service is onboarded to pipelines and continuously deploying to Staffship, Dotcom, EU Stamp and the Australia stamp. It blocks on deployment failures to any stamp.
- [ ] Your service is working as expected in Proxima and does not expose tenant suffixes in UI and API customer facing experiences
- [ ] Your service has completed a bug bash on the Proxima Australia Stamp, and you’re ready to accept bug reports and resolve bugs per [SLOs](https://github.com/github/engineering/discussions/3484).
- [ ] Your service has metrics, dashboards, and alerting in place for the Proxima Australia Stamp
- [ ] Any low effort high ROI automation is implemented
- [ ] You have updated [this spreadsheet](https://docs.google.com/spreadsheets/d/1GS227JrntqLBkHbDYwIQfFAGAOmwuMvtXLGmnxJU6a0/edit#gid=0) with the estimated effort and time savings of implementing automation for your area (if not implemented this quarter).
```
